local_backend: true

backend:
  name: git-gateway
  branch: turbo

media_folder: static/media/uploads
public_folder: /media/uploads

publish_mode: editorial_workflow

slug:
  encoding: ascii
  clean_accents: true

i18n:
  structure: multiple_files
  locales: [en, de, si]

collections:
  - name: posts
    label: Posts
    label_singular: post
    folder: content/posts
    create: true
    slug: "{{slug}}"
    i18n: true
    editor:
      preview: false
      notes: true
    fields: [
      {name: title, widget: string, i18n: true},
      {name: description, widget: text, i18n: true, required: false},
      {name: image, widget: image, i18n: duplicate, required: false},
      {name: body, widget: markdown, i18n: true},
      {name: author, widget: relation, i18n: duplicate, required: false, collection: authors, value_field: title, search_fields: [title]},
    ]

  - name: authors
    label: Authors
    label_singular: author
    folder: content/authors
    create: true
    slug: "{{slug}}"
    i18n: true
    editor:
      preview: false
    fields: [
      {name: title, widget: string, i18n: duplicate},
      {name: description, widget: text, i18n: true, required: false},
    ]

  - name: general
    label: General
    editor:
      preview: false
    files:
    - label: Site settings
      name: site-settings
      file: config.toml
      fields: [
        {name: title, widget: string},
        {label: Google Analytics ID, name: googleAnalytics, widget: string, required: false},
        {name: params, widget: object, fields: [
          {name: description, widget: text},
          {name: image, widget: image},
        ]},
      ]
    - label: Cookies
      name: cookies
      file: data/cookies.json
      fields: [
        {name: text, widget: string},
        {name: confirm, widget: string},
        {name: more, widget: object, fields: [
          {name: text, widget: string},
          {name: href, widget: string},
        ]},
      ]
    - label: Footer
      name: footer
      file: data/footer.json
      fields: [
        {name: copyright, widget: string}
      ]
