local_backend: true

backend:
  name: turbo-github
  repo: poslovnimediji/decap-cms-tester
  branch: turbo
  turbo_site_id: 7eb3acad-ddf7-4656-afd3-fd0652f69b44
  turbo_config_url: https://ioltadnfuvnndhbzbagl.supabase.co/functions/v1/config
  turbo_admin_url: https://develop--decap-turbo.netlify.app

media_folder: static/media/uploads
public_folder: /media/uploads

slug:
  encoding: ascii
  clean_accents: true

i18n:
  structure: multiple_files
  locales: [en, de, si]

collections:
  - name: posts
    label: Posts
    label_singular: post
    folder: content/posts
    create: true
    slug: "{{slug}}"
    i18n: true
    editor:
      preview: false
    fields: [
      {name: title, widget: string, i18n: true},
      {name: description, widget: text, i18n: true},
      {name: image, widget: image, i18n: duplicate, required: false},
      {name: body, widget: markdown, i18n: true},
    ]

  - name: general
    label: General
    editor:
      preview: false
    files:
    - label: Site settings
      name: site-settings
      file: config.toml
      fields: [
        {name: title, widget: string},
        {label: Google Analytics ID, name: googleAnalytics, widget: string, required: false},
        {name: params, widget: object, fields: [
          {name: description, widget: text},
          {name: image, widget: image},
        ]},
      ]
    - label: Cookies
      name: cookies
      file: data/cookies.json
      fields: [
        {name: text, widget: string},
        {name: confirm, widget: string},
        {name: more, widget: object, fields: [
          {name: text, widget: string},
          {name: href, widget: string},
        ]},
      ]
    - label: Footer
      name: footer
      file: data/footer.json
      fields: [
        {name: copyright, widget: string}
      ]
